spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  liquibase:
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#    show-sql: true

logging:
  level:
    root: error